from real_bonus_calculator import BonusDataLoader, BonusCalculator
from pathlib import Path

loader = BonusDataLoader(str(Path.cwd()))
print('folder', Path.cwd())
settings = loader.load_bonus_settings()
print('settings', settings)
weights = loader.load_metric_weights()
print('weights keys', list(weights.keys()))
plans = loader.load_monthly_plans()
print('plans loaded', plans.keys())
print('service plan march', plans.get('План продаж по продажи услуг', {}).get('Март'))
print('spare plan march', plans.get('План продаж по Запасным Частям', {}).get('Март'))
serv = loader.load_services_facts()
print('services facts count', len(serv))
print('first services fact', serv[:5])
spare = loader.load_spare_parts_facts()
print('spare facts count', len(spare))
print('first spare fact', spare[:5])
marg = loader.load_marginality_facts()
print('marginality count', len(marg))
print('sample marginality', list(marg.items())[:5])
other = loader.load_other_facts()
print('other facts', other)
calculator = BonusCalculator(loader)
result = calculator.calculate_for_month('Март')
print('result', result)
